server:
  port: 8080  # 服务器端口
spring:
  application:
    name: jhwjl-server  # 应用名称
  datasource:
    url: jdbc:mysql://${mysql.host}:${mysql.port}/jhwjl?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${mysql.username}
    password: ${mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  data:
    redis:
      host: ${redis.host}
      password: ${redis.password}
      port: ${redis.port}
  rabbitmq:
    host: ${rabbitmq.host}
    port: ${rabbitmq.port}
    username: ${rabbitmq.username}
    password: ${rabbitmq.password}
    virtual-host: ${rabbitmq.virtual-host}

jhwjl:
  jwt:
    secret: ${jwt.secret}  # 加密密钥
    expiration: ${jwt.expire}   # 过期时间